### PR TITLE
Fix SendRecv with zero count

### PR DESCRIPTION
**Pull request by benson31**
I'm experiencing some hangs with RCCL that this simple fix appears to avert.

### CODE REVIEW

**Review by bvanessen — APPROVED** [review]

**Comment by ndryden** [comment]
If this gets us moving, that's perhaps okay, but I am concerned about this. We used to have these semantics, and changed them in 7b18833. This introduces some semantic differences between backends as a zero-length send or receive is valid in MPI (and can be used for synchronization, for example). There was previously a bug in NCCL regarding zero-length send/recv, but that was fixed in 2.12.10-1.

We should check whether this is the actual root cause and see whether we need to report a RCCL bug.

**Comment by ndryden** [comment]
> @ndryden Should we temporarily wrap these in an if ROCm block then to capture that it is related to a potential RCCL bug?

That's one option, but we should make sure it's actually a RCCL bug and not something elsewhere (e.g., mis-matched zero-length send/recvs).

**Comment by benson31** [comment]
After further testing, this seems to be the right way to go after all. Let the PR open/close thrashing begin!

**Comment by benson31** [comment]
Forgot to rebase before re-open. But I've taken care of that now.

**Comment by benson31** [comment]
I should note that this PR doesn't address `Send` or `Recv` operations, only the send/recv blocks inside a `SendRecv` operation.

**Review by ndryden — APPROVED** [review]

**Pull request merged**
